name: Sample Github action
on: push

jobs:
  list-files:
    name: Confirmation
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # JSONをパースしてoutputにセット(改行を入れるとoutputが機能しないため除去)
      # create-pipeline が実行されたときの戻り値からPipelineのIDを得る想定
      - id: read-created-pipeline-id
        name: Read pipeline ID from create-pipeline response
        run: echo "::set-output name=json1::$(cat pipeline-id.json | tr -d '\n' | tr -d '\r')"
      # 前stepでパースして得たPipelineのIDを表示
      # outputsに入れて渡さないと、コマンドからの出力はfromJsonで扱えない模様
      - id: show-created-pipeline-id
        name: Show pipeline ID
        run: echo ${{ fromJson(steps.read-created-pipeline-id.outputs.json1).pipelineId }}
      # jqを使ってJSONをパースし、任意の要素を特定してその値を得る
      # list-pipelinesからの戻り値を使って、Pipelineのnameから目的のIDを特定する想定
      - id: parse-pipelines
        name: Parse pipeline list
        run: |
          json2=$(cat list-pipelines.json | tr -d '\n' | tr -d '\r')
          id=$(echo "${json2}" | jq -r '.pipelineIdList | map(select(.name == "export-coupon-daily-JST0300_coupon_code"))[0].id')
          echo $id
  detect-differences:
    name: Differences
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: get-changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v18.6
      - id: list-diff
        name: List differences
        run: |
          echo "ADDED"
          added=(${{ steps.get-changed-files.outputs.added_files }})
          for a in ${added[@]}; do echo ${a}; done
          echo "MODIFIED"
          modified=(${{ steps.get-changed-files.outputs.modified_files }})
          for m in ${modified[@]}; do echo ${m}; done
          echo "DELETED"
          deleted=(${{ steps.get-changed-files.outputs.deleted_files }})
          for d in ${deleted[@]}; do echo ${d}; done
