name: Sample Github action
on: push

jobs:
  list-files:
    name: Confirmation
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # JSONをパースしてoutputにセット(改行を入れるとoutputが機能しないため除去)
      # create-pipeline が実行されたときの戻り値からPipelineのIDを得る想定
      - id: read-created-pipeline-id
        name: Read pipeline ID from create-pipeline response
        run: |
          pid=$(cat pipeline-id.json | tr -d '\n' | tr -d '\r' | jq -r .pipelineId)
          echo $pid
      # jqを使ってJSONをパースし、任意の要素を特定してその値を得る
      # list-pipelinesからの戻り値を使って、Pipelineのnameから目的のIDを特定する想定
      - id: output-pipelines
        name: Parse pipeline list
        run: echo "::set-output name=my_json::$(cat list-pipelines.json | tr -d '\n' | tr -d '\r' | tr -d ' ')"
      - id: show-pipelines
        name: Identify pipeline ID
        run: |
          json='${{ steps.output-pipelines.outputs.my_json }}'
          pname='rds-export-reserve-daily-JST0300_spot_address'
          id=$(echo ${json} | jq -r ".pipelineIdList[] | select(.name == \"${pname}\").id")
          echo "NAME = ${pname}, ID = ${id}"
  detect-differences:
    name: Differences
    runs-on: ubuntu-latest
    steps:
      # checkout
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # changed-files action を使って差分を検知
      - id: get-changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v18.6
      # 追加されたファイル群をリスト
      - id: list-added-files
        name: List added files
        if: steps.get-changed-files.outputs.added_files
        run: |
          echo "ADDED"
          added=(${{ steps.get-changed-files.outputs.added_files }})
          for a in ${added[@]}
          do
            echo ${a}
          done
      # 更新されたファイル群をリスト
      - id: list-modified-files
        name: List modified files
        if: steps.get-changed-files.outputs.modified_files
        run: |
          echo "MODIFIED"
          modified=(${{ steps.get-changed-files.outputs.modified_files }})
          for m in ${modified[@]}; do echo ${m}; done
      # 削除されたファイル群をリスト
      - id: list-deleted-files
        name: List deleted files
        if: steps.get-changed-files.outputs.deleted_files
        run: |
          echo "DELETED"
          deleted=(${{ steps.get-changed-files.outputs.deleted_files }})
          for d in ${deleted[@]}; do echo ${d}; done
