name: Sample Github action
on: push

jobs:
  list-files:
    name: Confirmation
    runs-on: ubuntu-latest
    steps:
      - id: echo
        name: Echo
        run: echo "Pushed."
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: test-git-command
        name: Test for git command usability
        run: git log --oneline
      # JSONをパースしてoutputにセット(改行を入れるとoutputが機能しないため除去)
      # create-pipeline が実行されたときの戻り値からPipelineのIDを得る想定
      - id: read-created-pipeline-id
        name: Read pipeline ID from create-pipeline response
        run: |
          json1=$(cat pipeline-id.json | tr -d '\n' | tr -d '\r')
          echo ${{ fromJson('${json1}').pipelineId }}
      # 
      - id: parse-pipelines
        name: Parse pipeline list
        run: |
          json2=$(cat list-pipelines.json | tr -d '\n' | tr -d '\r')
          id=$(echo "${json2}" | jq -r '.pipelineIdList | map(select(.name == "rds-export-coupon-hourly_friend_code"))[0].id')
          echo $id
